"""
olp_verify.py — Expert verification for OLP access.

Only verified experts can log drags. Verification is automatic:
upload a DEF file that was output by a real industry tool
(OpenROAD, Cadence Innovus, Synopsys ICC2, KLayout, etc.) for a chip
with >500 cells.

Detection: parse the DEF, look for tool-specific markers
(generator version strings, comment lines, etc.).
"""

import re
from pathlib import Path

from .olp_db import ExpertVerification, get_db


# Tool-specific signatures we look for in DEF files
TOOL_SIGNATURES = {
    "openroad": [
        r"# Generated by\s+OpenROAD",
        r"VERSION\s+(\d+\.\d+\.\d+).*OpenROAD",
        r"OpenROAD v\d+",
        r"openroad-app",
    ],
    "cadence_innovus": [
        r"# Innovus",
        r"Innovus\s+v\d+",
        r"Generated by Cadence Innovus",
    ],
    "synopsys_icc2": [
        r"# ICC2",
        r"Synopsys IC Compiler",
        r"ICC2 v\d+",
    ],
    "klayout": [
        r"# LVS Report",
        r"KLayout",
    ],
    "yosys": [
        r"yosys\s+\d+",
    ],
    "openroad_flow": [
        r"openroad-flow-scripts",
        r"flow.tcl",
    ],
}


def detect_industry_tool(def_content: str) -> str:
    """Detect which industry tool generated the DEF.

    Returns the tool name (one of TOOL_SIGNATURES) or "" if not detected.
    """
    for tool, patterns in TOOL_SIGNATURES.items():
        for pat in patterns:
            if re.search(pat, def_content, re.IGNORECASE):
                return tool
    return ""


def count_cells(def_content: str) -> int:
    """Count the number of components in a DEF file."""
    in_components = False
    count = 0
    for line in def_content.split("\n"):
        if "COMPONENTS" in line and "END" not in line:
            in_components = True
            continue
        if "END COMPONENTS" in line:
            in_components = False
            continue
        if in_components and line.strip().startswith("-"):
            count += 1
    return count


def verify_expert_from_def(user_id: str, def_path: str) -> dict:
    """Verify a user as a real expert by examining their uploaded DEF.

    Args:
        user_id: the user identifier
        def_path: path to a DEF file output by an industry tool

    Returns dict with:
        - verified: bool
        - method: "industry_def_upload" if verified, else "failed"
        - tool: which industry tool generated the DEF (if detected)
        - cells: number of cells in the design
        - reason: if not verified, why
    """
    p = Path(def_path)
    if not p.exists():
        return {"verified": False, "method": "failed", "reason": f"File not found: {def_path}"}

    try:
        content = p.read_text(errors="ignore")
    except Exception as e:
        return {"verified": False, "method": "failed", "reason": f"Could not read: {e}"}

    # Check tool
    tool = detect_industry_tool(content)
    if not tool:
        return {
            "verified": False,
            "method": "failed",
            "reason": "No industry tool signature detected. Please upload a DEF output by OpenROAD, Cadence Innovus, Synopsys ICC2, KLayout, or Yosys.",
        }

    # Check cell count
    n_cells = count_cells(content)
    if n_cells < 500:
        return {
            "verified": False,
            "method": "failed",
            "tool": tool,
            "cells": n_cells,
            "reason": f"Design has only {n_cells} cells; need at least 500 to be a meaningful real chip.",
        }

    # Verify
    ver = ExpertVerification(
        user_id=user_id,
        method="industry_def_upload",
        source_def_path=str(p),
        source_chip_cells=n_cells,
        source_tool=tool,
    )
    ver.save()
    return {
        "verified": True,
        "method": "industry_def_upload",
        "tool": tool,
        "cells": n_cells,
        "user_id": user_id,
    }


def is_verified_expert(user_id: str) -> bool:
    """Public helper: check if a user is verified."""
    from .olp_db import is_verified_expert as _is
    return _is(user_id)
